### ISSUE TITLE
pg_top.appdata.xml is broken

### ISSUE THREAD

**Issue by probonopd** [markwkm/pg_top#16]
Could it be that `pg_top.appdata.xml` is broken? Getting

```
./appstreamcli-x86_64.AppImage convert database/pg_top/pg_top.appdata.xml database/pg_top/appdata.yaml

Could not parse XML data.
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2142

**Comment by markwkm** [comment]
I've been building my AppImages on Centos 6 with:

```
% appimagetool-x86_64.AppImage --version
fuse: warning: library too old, some operations may not work
appimagetool, continuous build (commit effcebc), build 2084 built on 2019-05-01 21:02:41 UTC
```

Maybe I need to upgrade and see what else needs to change?

**Comment by probonopd** [comment]
No, it's just what is inside `pg_top.appdata.xml`. This has nothing to do with appimagetool.

**Comment by markwkm** [comment]
My bad, totally misunderstood.  I ran pg_top.appdata.xml through an XML
validator and I think I fixed it in
65ad4e07592d4fbded1d8ffbc8e7c2c273d0e329 .

**Comment by probonopd** [comment]
Thanks, please ping me once a new build is out that contains the fix, then I can re-run the test.

**Comment by markwkm** [comment]
@probonopd I've make a v4.0.0-beta1 release.  Let me know how that looks. :)

**Comment by probonopd** [comment]
Thanks, it worked.
