### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mariner1-1** [markwkm/pg_top#17]
pg_top segfaults on a standard ub18.04 with postgres11, the application doesn''t even start.

GDB:

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pg_top...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/pg_top 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555565e80 in get_process_info ()
(gdb) bt
#0  0x0000555555565e80 in get_process_info ()
#1  0x000055555555a1f3 in main ()
(gdb) quit

dmesg:

[   23.929368] pg_top[1908]: segfault at 56c97510 ip 000055a3562a1e80 sp 00007ffc54d2a6c0 error 6 in pg_top[55a356290000+18000]
[   70.147790] pg_top[2006]: segfault at 30a88510 ip 000055de2eef7e80 sp 00007ffcef621310 error 6 in pg_top[55de2eee6000+18000]
[  240.596241] pg_top[2491]: segfault at 3b950310 ip 000055b63a92ee80 sp 00007ffed5925ce0 error 6 in pg_top[55b63a91d000+18000]
[  319.391081] pg_top[3037]: segfault at 32954310 ip 000055ea3223ce80 sp 00007ffc2d2a5a50 error 6 in pg_top[55ea3222b000+18000]
[  324.512122] pg_top[3040]: segfault at fffffffff4e38310 ip 00005569f4654e80 sp 00007ffe87a40500 error 7 in pg_top[5569f4643000+18000]
[  327.651475] pg_top[3044]: segfault at 78b32310 ip 000055eb77008e80 sp 00007ffe465f7480 error 6 in pg_top[55eb76ff7000+18000]
[  333.550656] pg_top[3049]: segfault at 660724f0 ip 00005615649d5e80 sp 00007ffe8836b870 error 6 in pg_top[5615649c4000+18000]
[  576.234168] pg_top[4322]: segfault at ffffffff8e84eb20 ip 000055738dfdbe80 sp 00007fffc4a3b720 error 7 in pg_top[55738dfca000+18000]
[  583.480255] pg_top[4327]: segfault at 324ace80 ip 000055f6317b1e80 sp 00007ffdc8e8e8f0 error 6 in pg_top[55f6317a0000+18000]
[  890.785259] pg_top[6050]: segfault at fffffffff9350b00 ip 00005609f84d3e80 sp 00007fffbea733c0 error 7 in pg_top[5609f84c2000+18000]

strace:

sendto(3, "Q\0\0\0\"SET statement_timeout = '2s"..., 35, MSG_NOSIGNAL, NULL, 0) = 35
poll([{fd=3, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "C\0\0\0\10SET\0Z\0\0\0\5T", 16384, 0, NULL, NULL) = 15
sendto(3, "Q\0\0\1\364WITH lock_activity AS\n(\n   "..., 501, MSG_NOSIGNAL, NULL, 0) = 501
poll([{fd=3, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "T\0\0\0\273\0\7pid\0\0\0-\346\0\3\0\0\0\27\0\4\377\377\377\377\0\0que"..., 16384, 0, NULL, NULL) = 967
sendto(3, "Q\0\0\0\17ROLLBACK;;\0", 16, MSG_NOSIGNAL, NULL, 0) = 16
poll([{fd=3, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "C\0\0\0\rROLLBACK\0Z\0\0\0\5I", 16384, 0, NULL, NULL) = 20
openat(AT_FDCWD, "6294/cmdline", O_RDONLY) = 4
read(4, "postgres: postgres postgres [loc"..., 255) = 183
close(4)                                = 0
openat(AT_FDCWD, "6294/stat", O_RDONLY) = 4
read(4, "6294 (postgres) S 3978 6294 6294"..., 4095) = 317
close(4)                                = 0
openat(AT_FDCWD, "6294/io", O_RDONLY)   = 4
read(4, "rchar: 166935\nwchar: 1\nsyscr: 47"..., 4095) = 96
close(4)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2a556b00} ---
+++ killed by SIGSEGV (core dumped) +++

**Comment by markwkm** [comment]
I've taken an initial look but don't yet understand how the libraries
are different on Ubuntu 18.04.

My thoughts for the moment are that this might be related to where
reallocarray() might or might not be.  Based on the man pages
reallocarray() isn't provided by the version of libc6 on 18.04, but
instead by libbsd.

I noticed that the compiler is giving implicit warnings about
reallocarray() in machine/m_remote.c and machine/m_linux.c.  It looks
like they are both including bsd/stdlib.h already.

That's what I have at the moment...

**Comment by markwkm** [comment]
I think I fixed it: 10d34eadda4f46ef64fc37f620ea1bc903a5b8b8

Part of my initial confusion was that 'man -k' only found reallocarray()
in the libbsd manpage, but the libc malloc() manpage explained that
_GNU_SOURCE needs to be defined.
