### ISSUE TITLE
How can I use  .pgpass with pg_top?

### ISSUE THREAD

**Issue by MichaelDBA** [markwkm/pg_top#18]
I would like to use pg_top without providing a password on the commandline or being prompted for one.  Is there a way to get it from .pgpass file?

**Comment by markwkm** [comment]
Yeah, pg_top uses libpq so normal .pgpass considerations apply.  Are you having trouble with it?

**Comment by MichaelDBA** [comment]
ahhh, my bad, I was using the -W parm which asks for password prompt.
