### ISSUE TITLE
No pg_top for PostgreSQL 17?

### ISSUE THREAD

**Issue by julienc256** [markwkm/pg_top#21]
Hello,

I used to retrieve the rpm **pg_top** package here :
https://download.postgresql.org/pub/repos/yum/versionPostgreSQL/redhat/rhel-8-x86_64/

### Examples :
**For PostgreSQL15:**
- link is : https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-8-x86_64/
- name is : pg_top_15-3.7.0-7.rhel8.x86_64.rpm

**For PostgreSQL16:**
- link is : https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-8-x86_64/
- name is : pg_top_16-3.7.0-7.rhel8.x86_64.rpm

But since PostgreSQL17, **pg_top** is no more present !!!
There is no **pg_top** package here : https://download.postgresql.org/pub/repos/yum/17/redhat/rhel-8-x86_64/

What is the reason for the absence of pg_top for PostgreSQL 17?

**Comment by markwkm** [comment]
We're not involved in any packaging, but the contact information for the community packagers is: https://yum.postgresql.org/contact/

Quickly searching their bug tracker for pg_top, I don't see any issues filed.  I suggested opening a ticket there.

**Comment by markwkm** [comment]
I just heard that the rpm has been added, but I haven't verified myself...
