### ISSUE TITLE
automake issues on Fedora 21

### ISSUE THREAD

**Issue by devrimgunduz** [markwkm/pg_top#7]
Hi,

I'm seeing these with automake 1.14.1 on Fedora 21:
- sh autogen.sh
  configure.ac:57: installing './compile'
  configure.ac:11: installing './install-sh'
  configure.ac:11: installing './missing'
  Makefile.am:14: warning: source file 'machine/m_remote.c' is in a subdirectory,
  Makefile.am:14: but option 'subdir-objects' is disabled
  automake: warning: possible forward-incompatibility.
  automake: At least a source file is in a subdirectory, but the 'subdir-objects'
  automake: automake option hasn't been enabled.  For now, the corresponding output
  automake: object file(s) will be placed in the top-level directory.  However,
  automake: this behaviour will change in future Automake versions: they will
  automake: unconditionally cause object files to be placed in the same subdirectory
  automake: of the corresponding sources.
  automake: You are advised to start using 'subdir-objects' option throughout your
  automake: project, to avoid future incompatibilities.
  Makefile.am:14: warning: source file 'machine/m_common.c' is in a subdirectory,
  Makefile.am:14: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_aix43.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_aix5.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_decosf1.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_freebsd.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_hpux10.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_hpux7.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_hpux9.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_irix5.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_irixsgi.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_linux.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_linuxthr.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_macosx.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_netbsd.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_openbsd.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_sco5.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_sunos4.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_sunos5.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_svr4.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am:17: warning: source file 'machine/m_svr5.c' is in a subdirectory,
  Makefile.am:17: but option 'subdir-objects' is disabled
  Makefile.am: installing './depcomp'

Cheers ,Devrim

**Comment by markwkm** [comment]
I tried this on Fedora 25 with automake 1.15-7:
```
$ ./autogen.sh
configure.ac:57: installing './compile'
```

Hopefully this is taken care of now, but let me know otherwise.
