### ISSUE TITLE
pg_top package

### ISSUE THREAD

**Issue by MichaelDBA** [markwkm/pg_top#9]
I don't see a pg_top package for the linux CentOS distro.  I remember in the past I was able to install it on ubuntu using "apt-get install pgtop".  Is the only way to get it for CentOS by downloading and compiling it from here?

**Comment by MichaelDBA** [comment]
Also, I see there have been no new commits since 2015.  Is this project still being maintained?

**Comment by MichaelDBA** [comment]
Also, there is no configure file after downloading and extracting the master.zip file.

**Comment by mw2q** [comment]
If pg_top is not available in the distro repositories, it is still available in the PGDG repository.  For example, for centos7 and postgresql 10, it would be pg_top10.  https://yum.postgresql.org/10/redhat/rhel-7-x86_64/repoview/letter_p.group.html

Oops, I haven't updated this mirror (will try to soon).  There have been some FreeBSD updates and the build system now uses cmake.

Prior to the cmake update, the `configure` script needs to be generated.  The `autogen.sh` script has the commands to generate the configure script.

**Comment by MichaelDBA** [comment]
thanks
